### ISSUE TITLE
Chào đội ngũ coder của UET Chatbot.

### ISSUE THREAD

**Issue by ngocthieu245** [uetchatbot/chatbot-ws#10]
Em đang là học sinh cấp 3, và cũng đam mê IT.
Em muốn tạo 1 chatbot giống với UET Chatbot nhưng do em chưa tìm hiểu về Node.Js từ trước nên có gặp đôi chút khó khăn trong quá trình cài đặt mã nguồn.
Em mong muốn được các anh giúp đỡ em cài đặt mã nguồn này.
Và cho em hỏi mã nguồn này có thể chạy trên server Cloud9 được không ạ?

Em cảm ơn,
Liên hệ với em qua Whatsapp +84965337946, hoặc Zalo +84965337946 ạ

**Comment by minhnt95** [comment]
Chào em, rất vui vì em quan tâm tới source code uetchatbot. 

Chatbot chỉ là một ứng dụng node js bình thường. vì vậy nó có thể triển khai lên tất cả các vps, host hỗ trợ nodejs

Hiện tại nhóm admin của uetchatbot bảo trì chỉ có 2 người nên bọn anh chỉ dám hỗ trợ về source (những lỗi liên quan tới việc sử dụng). Những yêu cầu về cài đặt rất mất công và thời gian nên a không thể hỗ trợ được. Em thông cảm.

**Comment by ngocthieu245** [comment]
Mã nguồn UET Chat bot yêu cầu phiên bản node js bao nhiêu ạ?
Và cho em hỏi mã nguồn này có thể chạy trên VPS Cloud9 được không ạ?

**Comment by minhnt95** [comment]
em chạy node bản 6.11.x (LTS). còn vps cloud 9 thì a ko rõ lắm

**Comment by ngocthieu245** [comment]
Em đã chạy được server và cài ssl cho domain rồi nhưng khi running server không sử dụng được ssl.
Cho em hỏi làm sao để cài ssl cho cổng chạy server ạ.

**Comment by bqcuong** [comment]
Ban thu tham khao link nay xem 
https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

**Comment by ngocthieu245** [comment]
http://ngocthieu.net:5310/
Chatbot của em đã mở với port 5310, vậy làm cách nào để active ssl cho port đó ạ?
