### ISSUE TITLE
Cần hỗ trợ về enabled ssl cho port chạy app chatbot

### ISSUE THREAD

**Issue by ngocthieu245** [uetchatbot/chatbot-ws#11]
Em đã chạy thành công app tại port 5310 nhưng không biết làm cách nào enabled ssl để setup webhook. Chứng chỉ SSL cho domain em cũng đã cài sẵn trên VPS rồi nhưng không biết config kiểu gì để có thể enabled SSL.

**Comment by minhnt95** [comment]
Sử dụng Google đi em, các vấn đề này có hướng dẫn hết mà:
- Deploy nodejs app production on ubuntu: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
- Config SSL: http://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by ngocthieu245** [comment]
Em đã chạy thành công app tại https://ngocthieu.com nhưng lại hiện thế này và không thể xác nhận webhook 
{"statusCode":404,"error":"Not Found"}
Tại sao lại bị như vậy ạ?

**Comment by minhnt95** [comment]
Thế là chạy rồi đó em. 
Em dùng đường dẫn này cho fb webhook là ok: https://ngocthieu.com/webhook

**Comment by ngocthieu245** [comment]
Cảm ơn anh, em đã xác nhận webhook được rồi
