### ISSUE TITLE
Có thể cho mình hỏi 1 xíu được không?

### ISSUE THREAD

**Issue by pidzvnese** [uetchatbot/chatbot-ws#12]
Chào bạn,
mình đang muốn làm 1 chatbot như bạn theo hướng dẫn, có 1 số điều mình chưa hiểu lắm
- VPS cần yêu cầu những cài đặt nào (Nginx, Apache ...)?
- Cài đặt source code đặt tại thư mục nào?
- Callback URL là gì?

Bạn có thể trả lời giúp mình không?
Cảm ơn bạn ^^

**Comment by bqcuong** [comment]
Chào bạn,
Mình xin được trả lời các câu hỏi của bạn
1. VPS không nhất thiết phải cài Nginx hay Apache. Server được chạy bằng NodeJS. Nhưng bọn mình khuyến khích bạn dùng Nginx để làm proxy server và cài đặt ssl.

2. Source code bạn có thể cài đặt bất cứ đâu, miễn bạn có quyền deploy mã nguồn tại thư mục đó

3. Callback URL là Webhook mà Messenger Send API sẽ gửi các request khi có user nhắn tin vào page. URL này sẽ có dạng như sau: *https://**domaincuaban**:6969/webhook*. Để hiểu thêm kỹ về các thông tin cấu hình này, bạn đọc document của Facebook về [Messenger Platform](https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup) nhé

**Comment by pidzvnese** [comment]
Chào bạn,
Cảm ơn bạn đã support mình, mình có 1 lỗi khi chạy con chatbot:
Khi mình run con chatbot kết quả trả về:
`[root@goccuaphong chatbot-ws]# npm start

> uetchatbot-ws@1.0.0 prestart /opt/chatbot-ws
> npm install

npm WARN The package knex is included as both a dev and production dependency.

up to date in 1.516s

> uetchatbot-ws@1.0.0 start /opt/chatbot-ws
> node index.js

(node:1594) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Server running at: http://goccuaphong.site:6969`

Nhưng mình làm tới bước cấu hình Facebook Webhook thì không được:

> Không thể xác thực URL. Callback verification failed with the following errors: curl_errno = 56; curl_error = Received HTTP code 503 from proxy after CONNECT; HTTP Status Code = 503; HTTP Message = Failed to connect to server

Lỗi này là do đâu vậy ạ? Cách giải quyết ntn ạ?
Cảm ơn bạn.

**Comment by bqcuong** [comment]
Lỗi 503 là Service Unavailable . Bạn hãy đảm bảo chắc chắn rằng từ bên ngoài có thể truy cập vào server của bạn nhé.

**Comment by pidzvnese** [comment]
Hôm qua mình quên open port 6969. Mình open port 6969 xong thì nó báo thế này 

> Không thể xác thực URL. Callback verification failed with the following errors: curl_errno = 28; curl_error = Operation timed out after 6000 milliseconds with 0 out of 0 bytes received; HTTP Status Code = 200; HTTP Message = Connection established

**Comment by minhnt95** [comment]
Hi @pidzvnese 

Những câu hỏi của bạn thuộc về việc vận hành ứng dụng nodejs trên cloud. Mình nghĩ đâu đó trên Google đã có câu trả lời cho bạn rồi nên việc tự xác định lỗi và sửa sẽ hiệu quả hơn bọn mình giải đáp. 
Hoặc nếu bạn chưa có kinh nghiệm triển khai ứng dụng nodejs thì có thể tìm hiểu thêm bằng từ khóa "Deploy nodejs application in production". Mình nghĩ làm quen một thời gian là sẽ quen và hiểu thôi :D

Mình sẽ đóng issue này tại đây. Cám ơn bạn!
