### ISSUE TITLE
Lỗi khi npm run database

### ISSUE THREAD

**Issue by tranhoaison** [uetchatbot/chatbot-ws#16]
Xin chào,
Mình gặp lỗi này khi chạy npm run database:

> `> uetchatbot-ws@1.0.0 database /root/chatbot-ws
> > knex migrate:latest
> 
> sh: 1: knex: not found
> 
> npm ERR! Linux 4.15.0-1026-gcp
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "database"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! uetchatbot-ws@1.0.0 database: `knex migrate:latest`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the uetchatbot-ws@1.0.0 database script 'knex migrate:latest'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the uetchatbot-ws package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     knex migrate:latest
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs uetchatbot-ws
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls uetchatbot-ws
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/chatbot-ws/npm-debug.log`

Rất mong được giúp đỡ, Mình xin cảm ơn nhiều :D

**Comment by minhnt95** [comment]
@tranhoaison 
Chào bạn,
Bạn đã chạy lệnh `npm install` để cài các thư viện cần thiết chưa?

**Comment by minhnt95** [comment]
@tranhoaison : bạn dùng phiên bản nodejs 8.x.x để chạy chatbot nhé
