### ISSUE TITLE
Không ghép cặp được.

### ISSUE THREAD

**Issue by stalangermin** [uetchatbot/chatbot-ws#17]
Xin chào mọi người,

Mình đã cài đặt gần thành công bot. duy chỉ có khi mình test bằng cách cho 2 người tham gia chatbot thì bot lại không ghép cặp. :-s 

Mong mọi người chỉ giùm mình phải làm sao để fix với ạ?

Xin cảm ơn tất cả. :D

**Comment by minhnt95** [comment]
@stalangermin : chào bạn, bạn có chạy câu lệnh khởi động như trong README.md không?
`pm2 start ecosystem.config.js`

**Comment by stalangermin** [comment]
@minhnt95 mình có chạy bạn ơi.

![image](https://user-images.githubusercontent.com/40028493/53803717-202dab00-3f78-11e9-856d-f4a8a9382819.png)

đây là webhooks: https://danangchat.com/webhooks

**Comment by minhnt95** [comment]
@stalangermin : bạn có thể cung cấp thêm log khi chạy pm2 của từng node app không? nhìn qua bên ngoài thì mình khó đoán được

**Comment by stalangermin** [comment]
@minhnt95

**Comment by stalangermin** [comment]
**Đây bạn ơi:**
`root@chatbot:~# pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2019-03-06T09:10:59: PM2 log: App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2        | 2019-03-06T09:10:59: PM2 log: App [schedule_chatbot:1] starting in -fork mode-
PM2        | 2019-03-06T09:10:59: PM2 log: App [schedule_chatbot:1] online
PM2        | 2019-03-06T09:11:00: PM2 log: App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2        | 2019-03-06T09:11:00: PM2 log: App [schedule_chatbot:1] starting in -fork mode-
PM2        | 2019-03-06T09:11:00: PM2 log: App [schedule_chatbot:1] online
PM2        | 2019-03-06T09:11:01: PM2 log: App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2        | 2019-03-06T09:11:01: PM2 log: App [schedule_chatbot:1] starting in -fork mode-
PM2        | 2019-03-06T09:11:01: PM2 log: App [schedule_chatbot:1] online
PM2        | 2019-03-06T09:11:03: PM2 log: App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2        | 2019-03-06T09:11:03: PM2 log: App [schedule_chatbot:1] starting in -fork mode-
PM2        | 2019-03-06T09:11:03: PM2 log: App [schedule_chatbot:1] online
PM2        | 2019-03-06T09:11:04: PM2 log: App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2        | 2019-03-06T09:11:04: PM2 log: App [schedule_chatbot:1] starting in -fork mode-
PM2        | 2019-03-06T09:11:04: PM2 log: App [schedule_chatbot:1] online

/root/.pm2/logs/schedule-chatbot-out-1.log last 15 lines:
/root/.pm2/logs/schedule-chatbot-error-1.log last 15 lines:
/root/.pm2/logs/chatbot-error-0.log last 15 lines:
0|chatbot  |     at Object.internals.handler (/root/chatbot-ws/node_modules/hapi/lib/handler.js:96:36)
0|chatbot  |     at request._protect.run (/root/chatbot-ws/node_modules/hapi/lib/handler.js:30:23)
0|chatbot  |     at module.exports.internals.Protect.internals.Protect.run (/root/chatbot-ws/node_modules/hapi/lib/protect.js:64:5)
0|chatbot  |     at exports.execute (/root/chatbot-ws/node_modules/hapi/lib/handler.js:24:22)
0|chatbot  |     at each (/root/chatbot-ws/node_modules/hapi/lib/request.js:384:16)
0|chatbot  |     at iterate (/root/chatbot-ws/node_modules/items/lib/index.js:36:13)
0|chatbot  |     at done (/root/chatbot-ws/node_modules/items/lib/index.js:28:25)
0|chatbot  |     at internals.Auth.payload (/root/chatbot-ws/node_modules/hapi/lib/auth.js:223:16)
0|chatbot  |     at each (/root/chatbot-ws/node_modules/hapi/lib/request.js:384:16)
0|chatbot  |     at iterate (/root/chatbot-ws/node_modules/items/lib/index.js:36:13)
0|chatbot  |     at done (/root/chatbot-ws/node_modules/items/lib/index.js:28:25)
0|chatbot  |     at onParsed (/root/chatbot-ws/node_modules/hapi/lib/route.js:402:20)
0|chatbot  | (node:1934) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
0|chatbot  | (node:1961) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
0|chatbot  | (node:2018) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

/root/.pm2/logs/chatbot-out-0.log last 15 lines:
0|chatbot  | Server running at: http://localhost:6969
0|chatbot  | Server running at: http://localhost:6969
0|chatbot  | deleteUser: None user is destroyed
0|chatbot  | Server running at: http://localhost:6969
0|chatbot  | deleteUser: None user is destroyed
0|chatbot  | Server running at: http://localhost:6969
0|chatbot  | Server running at: http://localhost:6969
0|chatbot  | Server running at: http://localhost:6969

PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
PM2      | App [schedule_chatbot:1] online
PM2      | App [schedule_chatbot:1] exited with code [0] via signal [SIGINT]
PM2      | App [schedule_chatbot:1] starting in -fork mode-
`

**Comment by minhnt95** [comment]
@stalangermin : xin lỗi bạn vì mình không trả lời bạn sớm hơn. Trong log này mình không tìm ra lỗi gì khả nghi cả. Mình đoán là có thể do settings, quyền phía Facebook đã thay đổi hoặc do version nodejs chăng (phiên bản chạy nodejs cho chatbot khuyến nghị là 8.6.x)
