### ISSUE TITLE
Về vấn đề port

### ISSUE THREAD

**Issue by nghminh163** [uetchatbot/chatbot-ws#6]
Cho em hỏi em đã mở router ở port 6969 nhưng mà đối với project của em create server http rồi listen port 6969 thì chạy ok nhưng mà em không thể start được chatbot UET ạ? Các anh có thể giúp em không ạ? Em cảm ơn ạ

**Comment by minhnt95** [comment]
em có thể show log không?

**Comment by nghminh163** [comment]
Log thì vẫn chạy nhưng mà em không thể dùng được ạ? Anh cho em hỏi anh dùng VPS của bên nào được không ạ

**Comment by minhnt95** [comment]
A nghĩ vps không phải vấn đề của em. Vì thực tế UETChatbot đã được chạy ở nhiều vps của các nhà cung cấp khác nhau (Z.com, Digital Ocean, ...) và hoạt động bình thường.
Em có thể tham khảo cách deploy 1 ứng dụng nodejs ở link sau: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by nghminh163** [comment]
Anh có thể cho em xin fb được không ạ :< Để em tiện inb ạ :( Em cảm ơn ạ

**Comment by nghminh163** [comment]
Anh ơi cho em hỏi: Em đã start server thành công nhưng mà khi mà add webhook vào Fb thì bị báo lỗi như sau
The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 28; curl_error = Operation timed out after 6000 milliseconds with 0 out of 0 bytes received; HTTP Message = Unknown Response Code

**Comment by minhnt95** [comment]
Em add fb a nhé: fb.com/TooNies1810
Lỗi kia em check thử link webhook xem đã hoạt động chưa (dán vào trình duyệt rồi enter)
ra kết quả như này là được:
`{"statusCode":422,"error":"Unprocessable Entity","message":"params is undefined!"}`
