### ISSUE TITLE
Host nào có NodeJs

### ISSUE THREAD

**Issue by fitthienngoc** [uetchatbot/chatbot-ws#7]
Hiện tại e đang dùng host của Stablehost.
Kiến thức e còn hẹn hẹp nên không biết rằng có NodeJS không nữa.
E đang dùng Cloud9 để test thử. E đang bị mắc tại sửa file .env 
Mong rằng a có thể trợ giúp em. Nếu mà Teamview được thì tuyệt quá. E rất muốn làm chatbot cho trường. Cảm ơn a!

**Comment by minhnt95** [comment]
Nếu em chưa có kiến thức về triển khai ứng dụng nodejs thì việc tìm hiểu sẽ khá vất vả.
Em có thể tham khảo cách tạo bot chat với người lạ đơn giản tại đây (được viết bởi một sinh viên UET): https://www.youtube.com/watch?v=7-s7Nae8atc
Sau khi hoạt động có số lượng người dùng tương đối rồi thì có thể quay lại sử dụng source code tạo chat bot sẽ đơn giản hơn

**Comment by fitthienngoc** [comment]
Cảm ơn a.  Mai e sẽ tìm hiểu.

Vào 02-08-2017 22:31, "Nguyễn Tiến Minh" <notifications@github.com> đã viết:
