### ISSUE TITLE
Lỗi tin nhắn lặp lại 2 lần

### ISSUE THREAD

**Issue by productbot123** [uetchatbot/chatbot-ws#8]
Mình viết code riêng, nhưng gặp lỗi này bạn có thể xem giúp mình không, mình đã tìm hiểu mà không biết sai đâu
Mỗi lần khi gửi tin nhắn thì bot lại trả lời lặp lại câu đó đến 2 lần. cảm ơn bạn

`<?php
// parameters
$hubVerifyToken = 'hubVerifyToken ';
$accessToken = "token";

// check token at setup
if ($_REQUEST['hub_verify_token'] === $hubVerifyToken) {
  echo $_REQUEST['hub_challenge'];
  exit;
}

// handle bot's anwser
$input = json_decode(file_get_contents('php://input'), true);

$senderId = $input['entry'][0]['messaging'][0]['sender']['id'];
$messageText = $input['entry'][0]['messaging'][0]['message']['text'];

$answer = "I don't understand. Ask me 'hi'.";
if($messageText == "hi") {
    $answer = "Hello";
}

$response = [
    'recipient' => [ 'id' => $senderId ],
    'message' => [ 'text' => $answer ]
];
$ch = curl_init('https://graph.facebook.com/v2.6/me/messages?access_token='.$accessToken);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($response));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
curl_exec($ch);
curl_close($ch);
`

**Comment by minhnt95** [comment]
bạn ơi mình ko biết PHP 😭

**Comment by productbot123** [comment]
Hic. Mình không biết Javascript

**Comment by minhnt95** [comment]
Nếu không phải lỗi do code thì có thể lỗi do config sai webhook trên fb console. bạn thử log xem có đúng req đó bị gọi 2 lần ko là rõ

**Comment by productbot123** [comment]
uhm
