### ISSUE TITLE
Đôi chút góp ý

### ISSUE THREAD

**Issue by ngxson** [uetchatbot/chatbot-ws#9]
Hôm nay rảnh ngồi tham khảo code, mình có vài góp ý như sau, mong là sẽ giúp ích cho các bạn:

**scheduler/match-users.js**: hàng đợi chỉ bị thay đổi mỗi khi có người thả câu, chuyển hàm sang gọi lúc checkAndInsertUser sẽ hợp lý hơn, giảm query ko cần thiết tới db. Ngoài ra schedule nên dùng setInterval.

**app/services/webhook.js**: ở deletePairSession nên ghi lại pair vừa xong, thì lúc randomMatchUser sẽ tránh pair này. pair đó sẽ bị xóa khi 1 trong 2 người tìm đc partner mới.

**app/services/message-sender.js**: không nên dùng GenericMessage vì nó không có tính backward compatible.

**Comment by bqcuong** [comment]
Cảm ơn bạn đã góp ý.

**Comment by minhnt95** [comment]
Mình xin trả lời bạn về giải pháp của chatbot:
**scheduler/match-users.js**: thuật toán ghép cặp chạy theo đệ quy, tức là mỗi 1 giây, việc ghép cặp sẽ được thực hiện một lần. Do việc thao tác với cơ sở dữ liệu có thể gây trễ với thời gian không biết trước, nên mình chạy đồng bộ, khi task ghép cặp trước chạy xong mới tiếp tục phiên ghép cặp sau 1s. Việc này đảm bảo dữ liệu toàn vẹn cho các phiên chat. (lí giải tại sao mình không dùng setInterval)

**app/services/message-sender.js:**: Có một số thông báo của chatbot như "cá đã cắn câu" hoặc "kết thúc phiên", ... không yêu cầu tương tác thì mình dùng GenericMessage. ngoài ra một số đặc biệt có dùng thêm quick replies. Điều này là chủ ý của mình để tạo ra trải nghiệm tốt nhất.

Cám ơn bạn đã có góp ý cho nhóm mình.
